# This file is a template, and might need editing before it works on your project.
# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: docker:19.03.8

variables:
  # When using dind service we need to instruct docker, to talk with the
  # daemon started inside of the service. The daemon is available with
  # a network connection instead of the default /var/run/docker.sock socket.
  #
  # The 'docker' hostname is the alias of the service container as described at
  # https://docs.gitlab.com/ee/ci/docker/using_docker_images.html#accessing-the-services
  #
  # Note that if you're using GitLab Runner 12.7 or earlier with the Kubernetes executor and Kubernetes 1.6 or earlier,
  # the variable must be set to tcp://localhost:2375 because of how the
  # Kubernetes executor connects services to the job container
  # DOCKER_HOST: tcp://localhost:2375
  #
  DOCKER_HOST: tcp://docker:2375
  #
  # This will instruct Docker not to start over TLS.
  DOCKER_TLS_CERTDIR: ""

services:
  - docker:19.03.8-dind


stages:

- test
- build
- release
- deploy

test:
  stage: test
  image: node:10.16.3
  script:
    - cd examples/12-factor-app-v1/
    - npm install
    - npm run test

build:
  before_script:
    - docker info
  stage: build
  script:
    - cd examples/12-factor-app-v1/
    - docker build -t 12factor:latest .
    - docker images

release:
  stage: release
  script:
    - cd examples/12-factor-app-v1/
    - echo pushing to artifactory

deploy:
  stage: deploy
  script:
    - cd examples/12-factor-app-v1/
    - echo change deployment-manifest.yml
    - echo kubectl apply -f deployment-manifest.yml
    
